server {
    listen 80;
    server_name _;

    # Servir les fichiers statiques
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Health check
    location /health {
        return 200 'OK';
        add_header Content-Type text/plain;
    }

    # Proxy vers service-users
    location /api/users {
        proxy_pass http://service-users:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy vers service-products
    location /api/products {
        proxy_pass http://service-products:3002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}